-- A PROFECIA V65 + PATCH
-- Persistência definitiva dos Players em linhas separadas.
-- Execute no SQL Editor do Supabase UMA vez.

create table if not exists public.a_profecia_players (
  id text primary key,
  login text not null,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  deleted_at timestamptz null
);

create unique index if not exists a_profecia_players_login_lower_idx
  on public.a_profecia_players (lower(login));

alter table public.a_profecia_players enable row level security;

drop policy if exists "public read players" on public.a_profecia_players;
drop policy if exists "public insert players" on public.a_profecia_players;
drop policy if exists "public update players" on public.a_profecia_players;

create policy "public read players" on public.a_profecia_players
  for select using (true);

create policy "public insert players" on public.a_profecia_players
  for insert with check (true);

create policy "public update players" on public.a_profecia_players
  for update using (true) with check (true);

-- Migração automática do antigo documento global.
-- Só insere jogadores que ainda não existem na tabela nova.
insert into public.a_profecia_players (id, login, data, updated_at, deleted_at)
select
  coalesce(nullif(trim(p->>'id'), ''), 'p-migrated-' || md5(p::text)),
  trim(p->>'login'),
  p || jsonb_build_object('_syncUpdatedAt', extract(epoch from now())::bigint * 1000),
  now(),
  null
from public.a_profecia_global g
cross join lateral jsonb_array_elements(coalesce(g.data->'players', '[]'::jsonb)) p
where g.id = 'main'
  and coalesce(trim(p->>'login'), '') <> ''
on conflict do nothing;

-- Realtime para sincronização entre celulares/computadores.
do $$
begin
  alter publication supabase_realtime add table public.a_profecia_players;
exception when duplicate_object then null;
end $$;

-- ---------------------------------------------------------------------------
-- V65 PATCH: proteção no servidor contra sobrescrita por estado antigo.
-- O cliente envia _syncUpdatedAt. O banco só aceita a alteração se ela não for
-- mais antiga que a linha que já existe.
-- ---------------------------------------------------------------------------
create or replace function public.a_profecia_upsert_player(
  p_id text,
  p_login text,
  p_data jsonb,
  p_sync_updated_at bigint,
  p_deleted_at timestamptz default null
)
returns public.a_profecia_players
language plpgsql
security definer
set search_path = public
as $$
declare
  existing public.a_profecia_players;
  result_row public.a_profecia_players;
  incoming_stamp bigint := coalesce(p_sync_updated_at, (extract(epoch from now()) * 1000)::bigint);
  incoming_data jsonb := jsonb_set(coalesce(p_data, '{}'::jsonb), '{_syncUpdatedAt}', to_jsonb(incoming_stamp), true);
begin
  if coalesce(trim(p_id), '') = '' or coalesce(trim(p_login), '') = '' then
    raise exception 'Player sem id ou login';
  end if;

  select * into existing
  from public.a_profecia_players
  where id = trim(p_id)
  for update;

  if found then
    if coalesce((existing.data->>'_syncUpdatedAt')::bigint, (extract(epoch from existing.updated_at) * 1000)::bigint, 0) > incoming_stamp then
      return existing;
    end if;
  end if;

  insert into public.a_profecia_players (id, login, data, updated_at, deleted_at)
  values (trim(p_id), trim(p_login), incoming_data, to_timestamp(incoming_stamp / 1000.0), p_deleted_at)
  on conflict (id) do update
    set login = excluded.login,
        data = excluded.data,
        updated_at = excluded.updated_at,
        deleted_at = excluded.deleted_at
    where coalesce((public.a_profecia_players.data->>'_syncUpdatedAt')::bigint, (extract(epoch from public.a_profecia_players.updated_at) * 1000)::bigint, 0) <= incoming_stamp;

  select * into result_row
  from public.a_profecia_players
  where id = trim(p_id);

  return result_row;
end;
$$;

grant execute on function public.a_profecia_upsert_player(text,text,jsonb,bigint,timestamptz) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Histórico automático dos Players.
-- Mesmo se um cliente tiver um problema, cada alteração fica registrada para
-- recuperação pelo proprietário do banco.
-- ---------------------------------------------------------------------------
create table if not exists public.a_profecia_players_history (
  history_id bigint generated by default as identity primary key,
  player_id text not null,
  action text not null,
  snapshot jsonb not null,
  recorded_at timestamptz not null default now()
);

alter table public.a_profecia_players_history enable row level security;

drop policy if exists "public read player history" on public.a_profecia_players_history;
drop policy if exists "public write player history" on public.a_profecia_players_history;

create or replace function public.a_profecia_players_history_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    insert into public.a_profecia_players_history(player_id, action, snapshot)
    values (old.id, 'DELETE', to_jsonb(old));
    return old;
  elsif tg_op = 'UPDATE' then
    if to_jsonb(new) is distinct from to_jsonb(old) then
      insert into public.a_profecia_players_history(player_id, action, snapshot)
      values (new.id, 'UPDATE', to_jsonb(new));
    end if;
    return new;
  else
    insert into public.a_profecia_players_history(player_id, action, snapshot)
    values (new.id, 'INSERT', to_jsonb(new));
    return new;
  end if;
end;
$$;

drop trigger if exists a_profecia_players_history_trg on public.a_profecia_players;
create trigger a_profecia_players_history_trg
after insert or update or delete on public.a_profecia_players
for each row execute function public.a_profecia_players_history_trigger();

-- Garantia explícita de que a tabela dos Players continua no Realtime.
do $$
begin
  alter publication supabase_realtime add table public.a_profecia_players;
exception when duplicate_object then null;
end $$;
